language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
  
before_script: cd 04-implementacao/hyperp_app_apresentacao

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
