language: java
sudo: false # faster builds

before_install: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk8
  
before_script: cd 04-implementacao/hyperp_app_apresentacao

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
deploy:
  provider: releases
  api_key: "d27ec3adc053ca01c626027bc5155ee330b53f09"
  file: "hyperp_app_apresentacao-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
